import json
import os
import re
import sys

import numpy as np
from openai import OpenAI
from torch.utils.data import DataLoader
from tqdm import tqdm

import openai

from API_test_202401Legacy.test_OpenAI_API import interact_with_GPT, interact_with_GPT_with_history

os.environ["http_proxy"] = "http://localhost:7890"
os.environ["https_proxy"] = "http://localhost:7890"

def extract_probability_from_json_format_response(gpt_response):
    """
    Extracts the probability of stock price rise from GPT's response.

    Parameters:
    gpt_response (str): The response generated by GPT.

    Returns:
    float: The extracted probability.
    """

    start_index = gpt_response.find('{')
    end_index = gpt_response.rfind('}')
    if start_index != -1 and end_index != -1 and start_index < end_index:
        gpt_response = gpt_response[start_index:end_index+1]

    response_dict = json.loads(gpt_response)
    
    results = []

    rise_prob = response_dict.get("probability_of_stock_price_rise")
    if rise_prob is not None:
        results.append(int(rise_prob) / 100)
    else:
        results.append("Rise probability not found")

    fall_prob = response_dict.get("probability_of_stock_price_fall")
    if fall_prob is not None:
        results.append(int(fall_prob) / 100)
    else:
        results.append("Fall probability not found")

    return results


def central_controller(news_id, headline, content, company_symbol, company_name, model_list):
    system_message = "You are an AI trained to analyze financial news and estimate the probability that the stock price of a specific company will rise or fall due to the news." + \
        "Your response should be in JSON format and include the following information: \n" + \
        "company_name: The name of the company. \n" + \
        "company_symbol: The stock symbol of the company. \n" + \
        "news_headline: The provided financial news headline. \n" + \
        "probability_of_stock_price_rise: The estimated probability (in percentage) that the stock price will rise due to this news. \n" + \
        "probability_of_stock_price_fall: The estimated probability (in percentage) that the stock price will fall due to this news. \n" + \
        "reasoning: A brief explanation of your reasoning. \n" + \
        "Format your response as follows: \n" + \
        "{ \n" + \
        '"company_name": "[Company Name]", \n' + \
        '"company_symbol": "[Company Symbol]", \n' + \
        '"news_headline": "[News Headline]", \n' + \
        '"probability_of_stock_price_rise": [Percentage], \n' + \
        '"probability_of_stock_price_fall": [Percentage], \n' + \
        '"reasoning": "[Brief explanation]" \n' + \
        "} \n" + \
        "Use the information provided and any general knowledge you have about the financial markets to support your analysis. \n" + \
        "Do not generate output that isn't in properly formatted JSON."
    user_message = f"Here's the company information and financial news: \n" + \
        f"Company Name: {company_name} \n" + \
        f"Company Symbol: {company_symbol} \n" + \
        f"News Headline: {headline} \n" + \
        f"News Content: {content}"

    agents = []
    for model in model_list:
        agent_dict = dict()
        agent_dict["model"] = model
        agent_dict["dialogue_history"] = [{"role": "system", "content": system_message}, {"role": "user", "content": user_message}]
        agent_dict["logprobs"] = []
        agents.append(agent_dict)

    results_dict = dict()
    results_dict["company_symbol"] = company_symbol
    results_dict["company_name"] = company_name
    results_dict["news_id"] = news_id
    results_dict["headline"] = headline
    results_dict["content"] = content
    results_dict["predictions"] = []

    T = 5
    for round_idx in range(T):
        results_one_round = dict()
        results_one_round["round_idx"] = round_idx
        results_one_round["model_predictions"] = []

        predictions = []
        for agent_dict in agents:
            model_name = agent_dict["model"]
            dialogue_history = agent_dict["dialogue_history"]
            response = interact_with_GPT_with_history(model_name, dialogue_history, None, logprobs=True)

            agent_dict["dialogue_history"] = response["dialogue_history"]
            agent_dict["logprobs"].append(response["logprobs"])

            pred = extract_probability_from_json_format_response(response["dialogue_history"][-1]["content"])
            predictions.append(pred)

            prediction_dict = {}
            prediction_dict["model_name"] = model_name
            prediction_dict["rise_prediction"] = pred[0]
            prediction_dict["fall_prediction"] = pred[1]
            results_one_round["model_predictions"].append(prediction_dict)

        results_dict["predictions"].append(results_one_round)

        for agent_idx, agent_dict in enumerate(agents):
            other_predictions = predictions.copy()
            other_predictions.pop(agent_idx)

            other_predictions_str = '"Other_predictions":[ \n'
            for other_pred in other_predictions:
                other_pred_dict = dict()
                if isinstance(other_pred[0], str):
                    other_pred_dict["probability_rise"] = other_pred[0]
                else:
                    other_pred_dict["probability_rise"] = int(other_pred[0] * 100)
                if isinstance(other_pred[1], str):
                    other_pred_dict["probability_fall"] = other_pred[1]
                else:
                    other_pred_dict["probability_fall"] = int(other_pred[1] * 100)
                other_predictions_str += f'{other_pred_dict} \n'
            other_predictions += "]"

            # create new user message
            user_message = f"Now I have received several predictions from some other experts. " + \
                f"I will provide you with these predictions. " + \
                f"Based on the financial news, information from previous rounds and these predictions from other experts, " + \
                f"Please estimate the probability that the stock price of the company will rise or fall due to the news. \n" + \
                f"{other_predictions_str}\n" + \
                f"Format your response in JSON as before."

            agent_dict["dialogue_history"].append({"role": "user", "content": user_message})

    for agent_dict in agents:
        model_name = agent_dict["model"]
        os.makedirs(f'log/multi_rounds/{model_name}', exist_ok=True)
        log_file_path = f'log/multi_rounds/{model_name}/{news_id}_json_format_response.json'
        with open(log_file_path, 'w') as f:
            json.dump(agent_dict, f)
    
    return results_dict


if __name__ == "__main__":
    
    """
    # Example GPT JSON response
    gpt_response = '''
    {
        "company_name": "ABC Corp",
        "company_symbol": "ABC",
        "news_headline": "Tech Giant ABC Corp Announces Major Acquisition of XYZ Ltd for $5 Billion",
        "probability_of_stock_price_rise": 70,
        "probability_of_stock_price_fall": 30,
        "reasoning": "The acquisition is generally positive, suggesting strategic expansion and potential long-term growth for ABC Corp. However, the high acquisition cost introduces some risk, tempering the probability."
    }
    '''

    # Extract the probability from the example JSON response
    probability = extract_probability_from_json_format_response(gpt_response)
    print(f"Extracted Probability: {probability}")
    """
    
    data_file_path = './data/financial_news_headlines/origin_data.json'
    with open(data_file_path, 'r') as f:
        data = json.load(f)
    
    prediction_results = []
    model_list = ['gpt-4o-2024-05-13', 'gpt-4o-mini-2024-07-18', 'gpt-4-turbo-2024-04-09', 'gpt-4-0613', 'gpt-3.5-turbo-0125']
    news_id = 0
    for company_symbol_dict in data:
        company_symbol = company_symbol_dict["company_symbol"]
        company_name = company_symbol_dict["company_name"]
        for news_dict in company_symbol_dict["financial_news"]:
            headline = news_dict["title"]
            content = news_dict["content"]

            results_dict = central_controller(news_id, headline, content, company_symbol, company_name, model_list)

            news_id += 1
            prediction_results.append(results_dict)

    results_file_path = "./results/LLM_predictions/multi_rounds_json_format_response.json"
    with open(results_file_path, 'w') as f:
        json.dump(prediction_results, f)
